/*

 GAME.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 47

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define GameBank 0
extern unsigned char GameTLE0[];
extern unsigned char GameTLE1[];
extern unsigned char GameTLE2[];
extern unsigned char GameTLE3[];
extern unsigned char GameTLE4[];
extern unsigned char GameTLE5[];
extern unsigned char GameTLE6[];
extern unsigned char GameTLE7[];
extern unsigned char GameTLE8[];
extern unsigned char GameTLE9[];
extern unsigned char GameTLE10[];
extern unsigned char GameTLE11[];
extern unsigned char GameTLE12[];
extern unsigned char GameTLE13[];
extern unsigned char GameTLE14[];
extern unsigned char GameTLE15[];
extern unsigned char GameTLE16[];
extern unsigned char GameTLE17[];
extern unsigned char GameTLE18[];
extern unsigned char GameTLE19[];
extern unsigned char GameTLE20[];
extern unsigned char GameTLE21[];
extern unsigned char GameTLE22[];
extern unsigned char GameTLE23[];
extern unsigned char GameTLE24[];
extern unsigned char GameTLE25[];
extern unsigned char GameTLE26[];
extern unsigned char GameTLE27[];
extern unsigned char GameTLE28[];
extern unsigned char GameTLE29[];
extern unsigned char GameTLE30[];
extern unsigned char GameTLE31[];
extern unsigned char GameTLE32[];
extern unsigned char GameTLE33[];
extern unsigned char GameTLE34[];
extern unsigned char GameTLE35[];
extern unsigned char GameTLE36[];
extern unsigned char GameTLE37[];
extern unsigned char GameTLE38[];
extern unsigned char GameTLE39[];
extern unsigned char GameTLE40[];
extern unsigned char GameTLE41[];
extern unsigned char GameTLE42[];
extern unsigned char GameTLE43[];
extern unsigned char GameTLE44[];
extern unsigned char GameTLE45[];
extern unsigned char GameTLE46[];
extern unsigned char GameTLE47[];

/* End of GAME.H */
