/*

 GANGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\Gang.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define GangMapWidth 20
#define GangMapHeight 18
#define GangMapBank 0

extern unsigned char GangMap[];

/* End of GANGMAP.H */
